services:
  - type: web
    name: Djangoblog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn My_first.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-d1mkc77diees73apamog-a
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

    postDeploy:
      - python manage.py migrate
      - python manage.py collectstatic --noinput
