# Generated by Django 4.2.23 on 2025-07-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keshav', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
